services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-sidecar
    restart: unless-stopped
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

