pipeline {
  agent any
  tools {
    dockerTool 'docker'
    nodejs 'nodejs'
  }

  environment {
    CI = 'true'
  }

  stages {
    stage('Install Dependencies') {
      steps {
        sh 'cd sidecar-react'
        sh 'npm i'
      }
    }

    stage('Build') {
      steps {
        sh 'cd sidecar-react'
        sh 'npm run build'
      }
    }
  }

  post {
    success {
      echo '✅ Build succeeded'
    }
    failure {
      echo '❌ Build failed'
    }
  }
}
