pipeline {
  agent {
    docker {
       image 'node:lts-buster-slim'
       args '-p 3000:3000'
      }
    }

  environment {
    CI = 'true'
  }

  stages {
    stage('Install Dependencies') {
      steps {
        sh 'npm i'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }
  }

  post {
    success {
      echo '✅ Build succeeded'
    }
    failure {
      echo '❌ Build failed'
    }
  }
}
